// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesTrend.WPF.Models;

#nullable disable

namespace SalesTrend.WPF.Migrations
{
    [DbContext(typeof(SalesTrendContext))]
    partial class SalesTrendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesTrend.WPF.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("Apartment")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("House")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("IndividualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LegalEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<int>("StreetId")
                        .HasColumnType("integer");

                    b.HasKey("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IndividualId")
                        .IsUnique();

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("StreetId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            Apartment = "114",
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            House = "1241",
                            LocalityId = 1,
                            StreetId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            Apartment = "124",
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            House = "1242",
                            LocalityId = 1,
                            StreetId = 1
                        },
                        new
                        {
                            AddressId = 3,
                            Apartment = "141",
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000003"),
                            House = "1234",
                            LocalityId = 1,
                            StreetId = 1
                        },
                        new
                        {
                            AddressId = 4,
                            Apartment = "134",
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000004"),
                            House = "1424",
                            LocalityId = 2,
                            StreetId = 2
                        },
                        new
                        {
                            AddressId = 5,
                            Apartment = "141",
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000005"),
                            House = "1524",
                            LocalityId = 2,
                            StreetId = 2
                        },
                        new
                        {
                            AddressId = 6,
                            Apartment = "144",
                            House = "1624",
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000001"),
                            LocalityId = 2,
                            StreetId = 2
                        },
                        new
                        {
                            AddressId = 7,
                            Apartment = "14",
                            House = "1274",
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000002"),
                            LocalityId = 3,
                            StreetId = 3
                        },
                        new
                        {
                            AddressId = 8,
                            Apartment = "514",
                            House = "1124",
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            LocalityId = 3,
                            StreetId = 3
                        },
                        new
                        {
                            AddressId = 9,
                            Apartment = "124",
                            House = "1242",
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000004"),
                            LocalityId = 3,
                            StreetId = 3
                        },
                        new
                        {
                            AddressId = 10,
                            Apartment = "214",
                            House = "124",
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000005"),
                            LocalityId = 4,
                            StreetId = 4
                        },
                        new
                        {
                            AddressId = 11,
                            Apartment = "714",
                            House = "124",
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000001"),
                            LocalityId = 4,
                            StreetId = 4
                        },
                        new
                        {
                            AddressId = 12,
                            Apartment = "814",
                            House = "124",
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000002"),
                            LocalityId = 4,
                            StreetId = 4
                        },
                        new
                        {
                            AddressId = 13,
                            Apartment = "14",
                            House = "444",
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000003"),
                            LocalityId = 5,
                            StreetId = 5
                        },
                        new
                        {
                            AddressId = 14,
                            Apartment = "194",
                            House = "111",
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000004"),
                            LocalityId = 5,
                            StreetId = 5
                        },
                        new
                        {
                            AddressId = 15,
                            Apartment = "149",
                            House = "222",
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000005"),
                            LocalityId = 5,
                            StreetId = 5
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ClientOrder", b =>
                {
                    b.Property<int>("ClientOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientOrderId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientOrderId");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientOrder");

                    b.HasData(
                        new
                        {
                            ClientOrderId = 1,
                            ClientId = new Guid("00000000-0000-0000-0000-000000000001"),
                            OrderDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4749)
                        },
                        new
                        {
                            ClientOrderId = 2,
                            ClientId = new Guid("00000000-0000-0000-0000-000000000002"),
                            OrderDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4751)
                        },
                        new
                        {
                            ClientOrderId = 3,
                            ClientId = new Guid("00000000-0000-0000-0000-000000000003"),
                            OrderDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4753)
                        },
                        new
                        {
                            ClientOrderId = 4,
                            ClientId = new Guid("00000000-0000-0000-0000-000000000004"),
                            OrderDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4754)
                        },
                        new
                        {
                            ClientOrderId = 5,
                            ClientId = new Guid("00000000-0000-0000-0000-000000000005"),
                            OrderDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4755)
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ClientOrderProduct", b =>
                {
                    b.Property<int>("ClientOrderProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientOrderProductId"));

                    b.Property<int>("ClientOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ClientOrderProductId");

                    b.HasIndex("ClientOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ClientOrderProduct");

                    b.HasData(
                        new
                        {
                            ClientOrderProductId = 1,
                            ClientOrderId = 1,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            ClientOrderProductId = 2,
                            ClientOrderId = 1,
                            ProductId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            ClientOrderProductId = 3,
                            ClientOrderId = 1,
                            ProductId = 3,
                            Quantity = 6
                        },
                        new
                        {
                            ClientOrderProductId = 4,
                            ClientOrderId = 1,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            ClientOrderProductId = 5,
                            ClientOrderId = 2,
                            ProductId = 5,
                            Quantity = 2
                        },
                        new
                        {
                            ClientOrderProductId = 6,
                            ClientOrderId = 2,
                            ProductId = 6,
                            Quantity = 5
                        },
                        new
                        {
                            ClientOrderProductId = 7,
                            ClientOrderId = 2,
                            ProductId = 7,
                            Quantity = 8
                        },
                        new
                        {
                            ClientOrderProductId = 8,
                            ClientOrderId = 2,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            ClientOrderProductId = 9,
                            ClientOrderId = 3,
                            ProductId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            ClientOrderProductId = 10,
                            ClientOrderId = 3,
                            ProductId = 15,
                            Quantity = 5
                        },
                        new
                        {
                            ClientOrderProductId = 11,
                            ClientOrderId = 3,
                            ProductId = 14,
                            Quantity = 8
                        },
                        new
                        {
                            ClientOrderProductId = 12,
                            ClientOrderId = 3,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            ClientOrderProductId = 13,
                            ClientOrderId = 4,
                            ProductId = 12,
                            Quantity = 2
                        },
                        new
                        {
                            ClientOrderProductId = 14,
                            ClientOrderId = 4,
                            ProductId = 11,
                            Quantity = 5
                        },
                        new
                        {
                            ClientOrderProductId = 15,
                            ClientOrderId = 4,
                            ProductId = 10,
                            Quantity = 8
                        },
                        new
                        {
                            ClientOrderProductId = 16,
                            ClientOrderId = 4,
                            ProductId = 8,
                            Quantity = 1
                        },
                        new
                        {
                            ClientOrderProductId = 17,
                            ClientOrderId = 5,
                            ProductId = 9,
                            Quantity = 2
                        },
                        new
                        {
                            ClientOrderProductId = 18,
                            ClientOrderId = 5,
                            ProductId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            ClientOrderProductId = 19,
                            ClientOrderId = 5,
                            ProductId = 2,
                            Quantity = 8
                        },
                        new
                        {
                            ClientOrderProductId = 20,
                            ClientOrderId = 5,
                            ProductId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPersonFullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContactPersonFullName = "Иван Иванович Иванов",
                            Email = "email1@mail.ru",
                            Name = "ООО ТехноТрейд 1",
                            Url = "https://some-site1.com"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ContactPersonFullName = "Петр Петрович Петров",
                            Email = "email2@mail.ru",
                            Name = "ООО ТехноТрейд 2",
                            Url = "https://some-site2.com"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ContactPersonFullName = "Сергей Сергеевич Сергеев",
                            Email = "email3@mail.ru",
                            Name = "ООО ТехноТрейд 3",
                            Url = "https://some-site3.com"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ContactPersonFullName = "Алексей Алексеевич Алексеев",
                            Email = "email4@mail.ru",
                            Name = "ООО ТехноТрейд 4",
                            Url = "https://some-site4.com"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ContactPersonFullName = "Дмитрий Дмитриевич Дмитриев",
                            Email = "email5@mail.ru",
                            Name = "ООО ТехноТрейд 5",
                            Url = "https://some-site5.com"
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Individual", b =>
                {
                    b.Property<Guid>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PassportSerial")
                        .HasColumnType("integer");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TaxNumber")
                        .HasColumnType("integer");

                    b.HasKey("IndividualId");

                    b.ToTable("Individual");

                    b.HasData(
                        new
                        {
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000001"),
                            IssueDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4582),
                            IssuedBy = "УФМС",
                            Name = "Иван",
                            PassportNumber = 567890,
                            PassportSerial = 1234,
                            Patronymic = "Иванович",
                            Surname = "Иванов",
                            TaxNumber = 123456789
                        },
                        new
                        {
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000002"),
                            IssueDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4584),
                            IssuedBy = "УФМС",
                            Name = "Петр",
                            PassportNumber = 123456,
                            PassportSerial = 5678,
                            Patronymic = "Петрович",
                            Surname = "Петров",
                            TaxNumber = 987654321
                        },
                        new
                        {
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000003"),
                            IssueDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4586),
                            IssuedBy = "УФМС",
                            Name = "Сидор",
                            PassportNumber = 112233,
                            PassportSerial = 9101,
                            Patronymic = "Сидорович",
                            Surname = "Сидоров",
                            TaxNumber = 567890123
                        },
                        new
                        {
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000004"),
                            IssueDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4588),
                            IssuedBy = "УФМС",
                            Name = "Александр",
                            PassportNumber = 161718,
                            PassportSerial = 1415,
                            Patronymic = "Александрович",
                            Surname = "Александров",
                            TaxNumber = 234567890
                        },
                        new
                        {
                            IndividualId = new Guid("00000000-0000-0000-0000-000000000005"),
                            IssueDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4589),
                            IssuedBy = "УФМС",
                            Name = "Дмитрий",
                            PassportNumber = 212223,
                            PassportSerial = 1920,
                            Patronymic = "Дмитриевич",
                            Surname = "Дмитриев",
                            TaxNumber = 678901234
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.LegalEntity", b =>
                {
                    b.Property<Guid>("LegalEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactPersonFullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TaxNumber")
                        .HasColumnType("integer");

                    b.HasKey("LegalEntityId");

                    b.ToTable("LegalEntity");

                    b.HasData(
                        new
                        {
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContactPersonFullName = "Иванов Иван Иванович",
                            Email = "ivanov@example.com",
                            Name = "ООО ТехноТрейд",
                            TaxNumber = 123456789
                        },
                        new
                        {
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ContactPersonFullName = "Петров Петр Петрович",
                            Email = "petrov@example.com",
                            Name = "ЗАО ЭлектроМагазин",
                            TaxNumber = 987654321
                        },
                        new
                        {
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ContactPersonFullName = "Сидоров Сидор Сидорович",
                            Email = "sidorov@example.com",
                            Name = "ПАО Инновационные Решения",
                            TaxNumber = 567890123
                        },
                        new
                        {
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ContactPersonFullName = "Александров Александр Александрович",
                            Email = "alexandrov@example.com",
                            Name = "ООО Торговый Элит",
                            TaxNumber = 234567890
                        },
                        new
                        {
                            LegalEntityId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ContactPersonFullName = "Дмитриев Дмитрий Дмитриевич",
                            Email = "dmitriev@example.com",
                            Name = "ЗАО Продвинутые Технологии",
                            TaxNumber = 678901234
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Locality", b =>
                {
                    b.Property<int>("LocalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocalityId"));

                    b.Property<int>("LocalityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("LocalityId");

                    b.HasIndex("LocalityTypeId");

                    b.ToTable("Locality");

                    b.HasData(
                        new
                        {
                            LocalityId = 1,
                            LocalityTypeId = 1,
                            Name = "Оренбург",
                            ShortName = "Орен."
                        },
                        new
                        {
                            LocalityId = 2,
                            LocalityTypeId = 2,
                            Name = "Вязовка",
                            ShortName = "Вязовка"
                        },
                        new
                        {
                            LocalityId = 3,
                            LocalityTypeId = 3,
                            Name = "Березовка",
                            ShortName = "Березовк."
                        },
                        new
                        {
                            LocalityId = 4,
                            LocalityTypeId = 4,
                            Name = "Заборье",
                            ShortName = "Заборье"
                        },
                        new
                        {
                            LocalityId = 5,
                            LocalityTypeId = 5,
                            Name = "Черничка",
                            ShortName = "Чернич."
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.LocalityType", b =>
                {
                    b.Property<int>("LocalityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocalityTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("LocalityTypeId");

                    b.ToTable("LocalityType");

                    b.HasData(
                        new
                        {
                            LocalityTypeId = 1,
                            Name = "Город",
                            ShortName = "г."
                        },
                        new
                        {
                            LocalityTypeId = 2,
                            Name = "Поселок",
                            ShortName = "п."
                        },
                        new
                        {
                            LocalityTypeId = 3,
                            Name = "Деревня",
                            ShortName = "д."
                        },
                        new
                        {
                            LocalityTypeId = 4,
                            Name = "Хутор",
                            ShortName = "х."
                        },
                        new
                        {
                            LocalityTypeId = 5,
                            Name = "Село",
                            ShortName = "с."
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhoneId"));

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PhoneId");

                    b.HasIndex("EntityId");

                    b.ToTable("Phone");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 2,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 3,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 4,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 5,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 6,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 7,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 8,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 9,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 10,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 11,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 12,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 13,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 14,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PhoneNumber = "+78005553535"
                        },
                        new
                        {
                            PhoneId = 15,
                            EntityId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PhoneNumber = "+78005553535"
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.PriceList", b =>
                {
                    b.Property<int>("PriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceListId"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PriceListId");

                    b.HasIndex("CompanyId");

                    b.ToTable("PriceList");

                    b.HasData(
                        new
                        {
                            PriceListId = 1,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReleaseDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4369)
                        },
                        new
                        {
                            PriceListId = 2,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReleaseDate = new DateTime(2023, 11, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4373)
                        },
                        new
                        {
                            PriceListId = 3,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4386)
                        },
                        new
                        {
                            PriceListId = 4,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ReleaseDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4388)
                        },
                        new
                        {
                            PriceListId = 5,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ReleaseDate = new DateTime(2023, 11, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4389)
                        },
                        new
                        {
                            PriceListId = 6,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4390)
                        },
                        new
                        {
                            PriceListId = 7,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ReleaseDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4392)
                        },
                        new
                        {
                            PriceListId = 8,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ReleaseDate = new DateTime(2023, 11, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4393)
                        },
                        new
                        {
                            PriceListId = 9,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4394)
                        },
                        new
                        {
                            PriceListId = 10,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ReleaseDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4395)
                        },
                        new
                        {
                            PriceListId = 11,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ReleaseDate = new DateTime(2023, 11, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4397)
                        },
                        new
                        {
                            PriceListId = 12,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4398)
                        },
                        new
                        {
                            PriceListId = 13,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ReleaseDate = new DateTime(2023, 12, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4399)
                        },
                        new
                        {
                            PriceListId = 14,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ReleaseDate = new DateTime(2023, 11, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4400)
                        },
                        new
                        {
                            PriceListId = 15,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ReleaseDate = new DateTime(2023, 10, 18, 7, 4, 31, 143, DateTimeKind.Utc).AddTicks(4436)
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.PriceListProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("PriceListId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "PriceListId");

                    b.HasIndex("PriceListId");

                    b.ToTable("PriceListProduct");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PriceListId = 1,
                            Price = 100m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 1,
                            Price = 150m,
                            Quantity = 8
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 1,
                            Price = 200m,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 1,
                            Price = 120m,
                            Quantity = 3
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 1,
                            Price = 80m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 2,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 2,
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 2,
                            Price = 250m,
                            Quantity = 11
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 2,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 2,
                            Price = 180m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 3,
                            Price = 200m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 3,
                            Price = 130m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 3,
                            Price = 110m,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 3,
                            Price = 150m,
                            Quantity = 31
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 3,
                            Price = 110m,
                            Quantity = 16
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 4,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 4,
                            Price = 160m,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 4,
                            Price = 180m,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 4,
                            Price = 130m,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 4,
                            Price = 90m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 5,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 5,
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 5,
                            Price = 250m,
                            Quantity = 11
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 5,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 5,
                            Price = 180m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 6,
                            Price = 200m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 12,
                            PriceListId = 6,
                            Price = 130m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 13,
                            PriceListId = 6,
                            Price = 110m,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 6,
                            Price = 150m,
                            Quantity = 31
                        },
                        new
                        {
                            ProductId = 15,
                            PriceListId = 6,
                            Price = 110m,
                            Quantity = 16
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 7,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 7,
                            Price = 160m,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 7,
                            Price = 180m,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 7,
                            Price = 130m,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 7,
                            Price = 90m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 8,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 8,
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 8,
                            Price = 250m,
                            Quantity = 11
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 8,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 8,
                            Price = 180m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 9,
                            Price = 200m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 9,
                            Price = 130m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 7,
                            PriceListId = 9,
                            Price = 110m,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 8,
                            PriceListId = 9,
                            Price = 150m,
                            Quantity = 31
                        },
                        new
                        {
                            ProductId = 9,
                            PriceListId = 9,
                            Price = 110m,
                            Quantity = 16
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 10,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 10,
                            Price = 160m,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 10,
                            Price = 180m,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 10,
                            Price = 130m,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 10,
                            Price = 90m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 11,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 11,
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 11,
                            Price = 250m,
                            Quantity = 11
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 11,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 11,
                            Price = 180m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 3,
                            PriceListId = 12,
                            Price = 200m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 12,
                            Price = 130m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 11,
                            PriceListId = 12,
                            Price = 110m,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 2,
                            PriceListId = 12,
                            Price = 150m,
                            Quantity = 31
                        },
                        new
                        {
                            ProductId = 6,
                            PriceListId = 12,
                            Price = 110m,
                            Quantity = 16
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 13,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 13,
                            Price = 160m,
                            Quantity = 6
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 13,
                            Price = 180m,
                            Quantity = 12
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 13,
                            Price = 130m,
                            Quantity = 4
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 13,
                            Price = 90m,
                            Quantity = 20
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 14,
                            Price = 120m,
                            Quantity = 1
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 14,
                            Price = 110m,
                            Quantity = 18
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 14,
                            Price = 250m,
                            Quantity = 11
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 14,
                            Price = 110m,
                            Quantity = 7
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 14,
                            Price = 180m,
                            Quantity = 25
                        },
                        new
                        {
                            ProductId = 10,
                            PriceListId = 15,
                            Price = 200m,
                            Quantity = 15
                        },
                        new
                        {
                            ProductId = 1,
                            PriceListId = 15,
                            Price = 130m,
                            Quantity = 5
                        },
                        new
                        {
                            ProductId = 14,
                            PriceListId = 15,
                            Price = 110m,
                            Quantity = 2
                        },
                        new
                        {
                            ProductId = 4,
                            PriceListId = 15,
                            Price = 150m,
                            Quantity = 31
                        },
                        new
                        {
                            ProductId = 5,
                            PriceListId = 15,
                            Price = 110m,
                            Quantity = 16
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Article = "1KF42",
                            Name = "Смартфон",
                            ProductTypeId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Article = "2KF42",
                            Name = "Ноутбук",
                            ProductTypeId = 4
                        },
                        new
                        {
                            ProductId = 3,
                            Article = "3KF42",
                            Name = "Смарт-телевизор",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 4,
                            Article = "4KF42",
                            Name = "Цифровая камера",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 5,
                            Article = "5KF42",
                            Name = "Беспроводные наушники",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 6,
                            Article = "6KF42",
                            Name = "Фитнес-трекер",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 7,
                            Article = "7KF42",
                            Name = "Робот-пылесос",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 8,
                            Article = "8KF42",
                            Name = "Смарт-термостат",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 9,
                            Article = "9KF42",
                            Name = "Дрон",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 10,
                            Article = "10KF42",
                            Name = "Игровая консоль",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 11,
                            Article = "11KF42",
                            Name = "Наушники",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 12,
                            Article = "12KF42",
                            Name = "Планшет",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 13,
                            Article = "13KF42",
                            Name = "Смарт-часы",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 14,
                            Article = "14KF42",
                            Name = "Камера видеонаблюдения",
                            ProductTypeId = 5
                        },
                        new
                        {
                            ProductId = 15,
                            Article = "15KF42",
                            Name = "Электрическая зубная щетка",
                            ProductTypeId = 5
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            Name = "Смартфоны",
                            ShortName = "Смартфоны"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            Name = "Товары для дома",
                            ShortName = "Товары для дома"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            Name = "Одежда",
                            ShortName = "Одежда"
                        },
                        new
                        {
                            ProductTypeId = 4,
                            Name = "Ноутбуки",
                            ShortName = "Ноутбуки"
                        },
                        new
                        {
                            ProductTypeId = 5,
                            Name = "Прочая электроника",
                            ShortName = "Электроника"
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Street", b =>
                {
                    b.Property<int>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StreetId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StreetTypeId")
                        .HasColumnType("integer");

                    b.HasKey("StreetId");

                    b.HasIndex("StreetTypeId");

                    b.ToTable("Street");

                    b.HasData(
                        new
                        {
                            StreetId = 1,
                            Name = "Новая",
                            ShortName = "ул.",
                            StreetTypeId = 1
                        },
                        new
                        {
                            StreetId = 2,
                            Name = "Мира",
                            ShortName = "пр.",
                            StreetTypeId = 2
                        },
                        new
                        {
                            StreetId = 3,
                            Name = "Центральный",
                            ShortName = "бул.",
                            StreetTypeId = 3
                        },
                        new
                        {
                            StreetId = 4,
                            Name = "Молодежный",
                            ShortName = "пер.",
                            StreetTypeId = 4
                        },
                        new
                        {
                            StreetId = 5,
                            Name = "Луговой",
                            ShortName = "пр-д",
                            StreetTypeId = 5
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.StreetType", b =>
                {
                    b.Property<int>("StreetTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StreetTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("StreetTypeId");

                    b.ToTable("StreetType");

                    b.HasData(
                        new
                        {
                            StreetTypeId = 1,
                            Name = "Улица",
                            ShortName = "ул."
                        },
                        new
                        {
                            StreetTypeId = 2,
                            Name = "Проспект",
                            ShortName = "пр."
                        },
                        new
                        {
                            StreetTypeId = 3,
                            Name = "Бульвар",
                            ShortName = "бул."
                        },
                        new
                        {
                            StreetTypeId = 4,
                            Name = "Переулок",
                            ShortName = "пер."
                        },
                        new
                        {
                            StreetTypeId = 5,
                            Name = "Проезд",
                            ShortName = "пр-д"
                        });
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Address", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.Company", "Company")
                        .WithMany("Addresses")
                        .HasForeignKey("CompanyId");

                    b.HasOne("SalesTrend.WPF.Models.Individual", "Individual")
                        .WithOne("Address")
                        .HasForeignKey("SalesTrend.WPF.Models.Address", "IndividualId");

                    b.HasOne("SalesTrend.WPF.Models.LegalEntity", "LegalEntity")
                        .WithMany("Addresses")
                        .HasForeignKey("LegalEntityId");

                    b.HasOne("SalesTrend.WPF.Models.Locality", "Locality")
                        .WithMany("Addresses")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTrend.WPF.Models.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Individual");

                    b.Navigation("LegalEntity");

                    b.Navigation("Locality");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ClientOrder", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.Individual", "Individual")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTrend.WPF.Models.LegalEntity", "LegalEntity")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ClientOrderProduct", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.ClientOrder", "ClientOrder")
                        .WithMany("ClientOrderProducts")
                        .HasForeignKey("ClientOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTrend.WPF.Models.Product", "Product")
                        .WithMany("ClientOrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Locality", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.LocalityType", "LocalityType")
                        .WithMany("Localities")
                        .HasForeignKey("LocalityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalityType");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Phone", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.Company", "Company")
                        .WithMany("Phones")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTrend.WPF.Models.LegalEntity", "LegalEntity")
                        .WithMany("Phones")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("LegalEntity");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.PriceList", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.Company", "Company")
                        .WithMany("PriceLists")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.PriceListProduct", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.PriceList", "PriceList")
                        .WithMany("PriceListProducts")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesTrend.WPF.Models.Product", "Product")
                        .WithMany("PriceListProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Product", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Street", b =>
                {
                    b.HasOne("SalesTrend.WPF.Models.StreetType", "StreetType")
                        .WithMany()
                        .HasForeignKey("StreetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreetType");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ClientOrder", b =>
                {
                    b.Navigation("ClientOrderProducts");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Company", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");

                    b.Navigation("PriceLists");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Individual", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.LegalEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Locality", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.LocalityType", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.PriceList", b =>
                {
                    b.Navigation("PriceListProducts");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Product", b =>
                {
                    b.Navigation("ClientOrderProducts");

                    b.Navigation("PriceListProducts");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesTrend.WPF.Models.Street", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
